sudo: false
language: cpp
compiler:
  - gcc
addons:
  apt:
    packages:
    - arduino
before_script:
  - wget https://downloads.arduino.cc/arduino-cli/arduino-cli-0.3.2-alpha.preview-linux64.tar.bz2
  - tar xvf arduino-cli-0.3.2-alpha.preview-linux64.tar.bz2
  - chmod +x arduino-cli-0.3.2-alpha.preview-linux64
  - mkdir ~/.arduino15
  - ./arduino-cli-0.3.2-alpha.preview-linux64 core update-index --config-file arduino-cli.yaml 
  - ./arduino-cli-0.3.2-alpha.preview-linux64 core install esp8266:esp8266 arduino:avr --config-file arduino-cli.yaml
script:
  - ./test.sh
